### ISSUE TITLE
Update pelago/emogrifier dependency to ^2.0.0

### ISSUE THREAD

**Issue by oliverklee** [mailoptin/core#1]
Emogrifier 2.0.0 has been released, fixing a lot of bugs. If the new PHP >= 5.5 requirement is not a problem, the dependency should be updated to ^2.0.0. This also provides compatibility with PHP 7.2.

**Comment by collizo4sky** [comment]
We currently require PHP >= 5.4 hence we won't be updating to 2.0.0

**Comment by oliverklee** [comment]
If you would like to make the new Emogrifier available to at least the users with PHP >= 5.5, you can use this version requirement:

`"pelago/emogrifier": "^1.2.0 || ^2.0.0"`

This will then use the highest Emogrifier version that is available for the current platform.

**Comment by collizo4sky** [comment]
@oliverklee so basically, composer will check the PHP version of the current server and load the 2.0.0 version if its PHP >= 5.5 right?

But the thing is, we run a build script that download and install emogrifier before making a release. Since my dev server is PHP 7, this will download 2.0.0 and when a release is made, users of PHP < PHP 5.5 will get fatar error.

WIW mailoptin/core is not a re-useable library for public usage.

**Comment by oliverklee** [comment]
@collizo4sky Yes, that's correct.

Oh, in that case, having `"^1.2.0 || ^2.0.0"` indeed does not make sense.

I propose adding platform: php: 5.4 to your `composer.json`,  though, so that your build script will always create PHP 5.4-compatible packages.

In the phpList 4 project, we do it like this for exactly the same reason (for PHP 7.0 instead of 5.4, though, but it will work the same):
https://github.com/phpList/base-distribution/blob/master/composer.json#L54

**Comment by collizo4sky** [comment]
Done. Thanks.
